version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres-demo-transaction
    environment:
      POSTGRES_DB: ludito_demo
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Optional: init script only runs if DB doesn't exist
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - demo-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-transaction-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    command: [ "./wait-for-postgres.sh", "java", "-jar", "app.jar" ]
    working_dir: /app
    volumes:
      - ./target/demo-transaction-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - demo-network

volumes:
  pgdata:

networks:
  demo-network: